crop = Crop.create(name: "Cannabis", description: "Weed...")
variant = Variant.create(name: "Blueberry", description: "A Good Strain")
plan = Plan.create(name: "Fox Farm", description: "A Quality Nutrient Line...")
medium = Medium.create(name: "CoCo", description: "A growth medium")
Plant.create(crop_id: crop.id, variant_id: variant.id, medium_id: medium.id , plan_id: plan.id, start_date: Date.today)             
